
#include <stddef.h>                     // Defines NULL
#include <stdbool.h>                    // Defines true
#include <stdlib.h>                     // Defines EXIT_FAILURE
#include "definitions.h"                // SYS function prototypes

#include "application.h"
#include "Protocol/protocol.h"
#include <math.h>


 /** 
     * \defgroup appMainModule  Main Module 
     * \ingroup applicationModule
     *     
     * This section implements the data structures of the module
     *  @{
     */
volatile static bool exec_i2c = false;
volatile static bool alarm_VAC = true;
volatile static int alarm_vac_count = ALARM_VAC_TMO;

volatile static unsigned char led_fault_status = 0;
#define LED_FAULT_INITIALIZATION_FASE 0x1

volatile static unsigned char main_fase = 0;
#define MAIN_FASE_INIT_LOOP 0
#define MAIN_FASE_RUNNING_LOOP 1

//static unsigned char temperature = 0;

volatile static uint8_t trigger_time = 0;

#define _1024_ms_TriggerTime 0x1
#define _512_ms_TriggerTime 0x2
#define _7820_us_TriggerTime 0x4
#define _15_64_ms_TriggerTime 0x8

volatile static bool alarm_overcurrent = false;
volatile static bool target = false;
volatile static unsigned short DACVAL = 0;

static void mosfetActivation(bool state){
    #ifdef MOSFET_SWITCH_ENABLED
        if(state) uc_SHDOWN_Clear();
        else uc_SHDOWN_Set();
    #else
        uc_SHDOWN_Set();
    #endif

}


/**
 * This is the callback generated by the RTC module at the interrupt event.
 * 
 * @param intCause this is the cause of the interrupt event;
 * @param context this is the data pointer passed with the  RTC_Timer32CallbackRegister() routine;
 */
static void rtcEventHandler (RTC_TIMER32_INT_MASK intCause, uintptr_t context)
{
    // Periodic Interval Handler: Freq = 1024 / 2 ^ (n+3)
    
    if (intCause & RTC_TIMER32_INT_MASK_PER0) trigger_time |= _7820_us_TriggerTime;  // 7.82ms Interrupt
    if (intCause & RTC_TIMER32_INT_MASK_PER1) trigger_time |= _15_64_ms_TriggerTime; // 15.64ms Interrupt
    if (intCause & RTC_TIMER32_INT_MASK_PER6) trigger_time |= _512_ms_TriggerTime;  // 512 ms Interrupt
    if (intCause & RTC_TIMER32_INT_MASK_PER7) trigger_time |= _1024_ms_TriggerTime;  // 1024 ms Interrupt
    
}



// Conversion of the AC input
// 0xFFFF = 3.3V = 113.64 * 3.3 = 375 Vpk
// V = 375 * n / 65536
static volatile float VAC = 0;
static volatile float maxVAC = 0;
static volatile float minVAC = 0;
static volatile unsigned char inputFreq = 0;
static volatile bool  VAC_Initialize = false;

static volatile float Iref = 0;
static volatile float Iinput = 0;
static volatile float Ifollow = 0;
static volatile unsigned short DAC_IREF = 0;

static volatile float VOUT = 0;
static volatile float maxVOUT = 0;
static volatile float minVOUT = 0;
static volatile float IOUT = 0;

static void TC0callback(TC_TIMER_STATUS status, uintptr_t context){
#ifndef TEST_SWITCH
    return;
#endif

    static int count=0;
    count++;
    
    if(count < 4) uc_SHDOWN_Clear();
    else uc_SHDOWN_Set();
    if(count == 5) count = 0;
    
    LED4_Toggle();
}

#ifdef GET_FASE_FROM_VAC
static float getFaseFromVac(void){
    if( (maxVAC-minVAC) < VAC_INPUT/2) return 0;
    
    float fase = (VAC - minVAC) / (maxVAC-minVAC);
    if(fase > 1) return 1;
    if(fase < 0 ) return 0;
    return fase ;
}
#endif

#ifdef GET_FASE_FROM_SIN
static  float getFaseFromFunc(void){
    float fase = 0;
    static int time = 0;
    static bool synch = false;
    
    
    // Synch
    if((!synch) && (VAC < minVAC+VAC_THRESHOLD)){
        time = 0;
        synch = true;
    }else{
        time += AC_SMP_TIME_us;
        
        if(time >= 10 * (1000000/AC_FREQ)){ 
            time = 0;
            synch = false;
        }
        
    }

    // Sinusoide raddrizzata a 50Hz
    fase = sin(6.28 * AC_FREQ * (time+SIN_CORRECT_FASE_us)/1000000);
    if(fase < 0) fase = -fase;
    return fase;
}
#endif

static volatile int level = 0;

#ifdef TEST_REFERENCE
static void ExecTestReference(void){
    float fase = 0;
    float Ifollow = 0;
    static int time = 0; // useconds
    
    
    uc_SHDOWN_Clear();
    time += AC_SMP_TIME_us;
    if(time >= 50000){ 
       time = 0;
    }
   

    // Sinusoide raddrizzata a 50Hz
    fase = sin(6.28 * 50 * time/1000000);
    if(fase < 0) fase = -fase;
    Ifollow = (MAX_CURRENT * fase);  
    unsigned short DACVAL = DAC(Ifollow);
    
    DAC_DataWrite(DAC_CHANNEL_0,DACVAL);  
    return;
}
#endif

static void ExecControl(bool init){
    static float fase = 0;
    
    
    if(init){
        fase = 0;
        Iref = 0;
        Ifollow = 0;
        mosfetActivation(false);
        DAC_DataWrite(DAC_CHANNEL_0,0);        
        return;
    }
    
    
#ifdef RUN_CONST_VOLTAGE
    static float Inom = 0;
    bool update = false;
    
    float ival = 1.41 * (IOUT * VOUT) / (maxVAC) ;
    
    if(ival < Inom * 0.7) update = true;
    else if(ival > Inom * 1.3) update = true;
    Inom = ival;
    if(VOUT < TARGET_VOLTAGE-50) update = true;
    if(VOUT > TARGET_VOLTAGE + 30 ) update = true;
    if(VAC < minVAC + 5) update = true;
    
    
    if(VOUT < TARGET_VOLTAGE-100){
        level = 0;
        Inom = 3*Inom;
    }else if(VOUT < TARGET_VOLTAGE-50){
        level = 1;
        Inom = 3*Inom;//Inom = 2.2*Inom;
    }else if(VOUT < TARGET_VOLTAGE-20){
        level = 2;
        Inom = 3*Inom;//Inom = 1.8*Inom;
    }else if(VOUT < TARGET_VOLTAGE-10){
        level = 3;
        Inom = 2*Inom;//Inom = 1.4*Inom;
    }else if(VOUT < TARGET_VOLTAGE) {
        level = 5;
        Inom = 1.8*Inom;//Inom = Inom*1.2;
    }else if(VOUT < TARGET_VOLTAGE+10) {
        level = 5;
        Inom = Inom;
    }else if(VOUT < TARGET_VOLTAGE+20) {
        level = 5;
        Inom = 0.8 *Inom;
    }else if(VOUT < TARGET_VOLTAGE+30) {
        level = 5;
        Inom = 0.6 *Inom;
    }else if(VOUT > TARGET_VOLTAGE+30) {
        level = 6;
        Inom = 0.3 *Inom;
    }
    
    if(update){
        Iref = Inom;
        LED1_Set();
    }else LED1_Clear();

    if((VOUT < TARGET_VOLTAGE+10)&&(VOUT > TARGET_VOLTAGE-10))
    {
        LED2_Set();
    }else LED2_Clear();
    
    if(VOUT > 600) Iref= 0;
    
    // Massima corrente accettabile
    if(Iref >MAX_CURRENT) Iref = MAX_CURRENT;
#endif 
#ifdef RUN_CONST_CURRENT
    Iref = MAX_CURRENT;
#endif   
             
    
    #ifdef GET_FASE_FROM_VAC
        fase = getFaseFromVac();
    #endif
    #ifdef GET_FASE_FROM_SIN
        fase = getFaseFromFunc();
    #endif
    #ifdef GET_FASE_FROM_CONST
        fase = GET_FASE_FROM_CONST;
    #endif


    // Shape della corrente
    Ifollow = (Iref * fase);     
    DACVAL = DAC(Ifollow);
    DAC_DataWrite(DAC_CHANNEL_0,DACVAL);  
    
     // Se la tensione massima di ingresso è bassa interrompe l'inseguimento
    if(alarm_VAC)
    {
        mosfetActivation(false);
        return;
    }else{
        mosfetActivation(true);
    }
 
}

static bool ADC0Exec = false;

// 116 us Conversion Time
// 86 samples in a 100 Hz
// Durata: 4.2us
#define MAXMIN_VAC_CYCLES (10 * 10000/AC_SMP_TIME_us)

static void ADC0ExecProcedure(void){
    static unsigned short  cycles = MAXMIN_VAC_CYCLES;
    static float parzial_max = 0;
    static float parzial_min = 1000;
    
        
    WDT_Clear();   
    
    // VAC Sampling channel
    // GEts the current VAC
    

    // Massimo e minimo della tensione di ingresso
    if(VAC > parzial_max){
        parzial_max = VAC;
    }

    if(VAC < parzial_min){
        parzial_min = VAC;
    }

    // Every
    cycles--;        
    if(cycles == 0){
       maxVAC =  parzial_max;
       minVAC =  parzial_min;
       if(minVAC > maxVAC) minVAC = maxVAC;
       parzial_max = 0;
       parzial_min = 1000;
       cycles = MAXMIN_VAC_CYCLES;
    }

    // Scrittura della corrente di riferimento     
    VOUT = (float) ADC1_ConversionResultGet() *  0.0106 ;/// 1.6;
    
    if(maxVAC < MIN_VACIN){
        alarm_VAC = true;
        alarm_vac_count = ALARM_VAC_TMO; // 15ms unit
    }

   

    #ifdef TEST_SWITCH
        DAC_DataWrite(DAC_CHANNEL_0,65535);
        return;
    #endif

    #ifdef TEST_REFERENCE
        ExecTestReference();
        return;
    #endif

    ExecControl(false);
    
    return;
}

static bool isVAC = true;
static void ADC0_Callback(ADC_STATUS status, uintptr_t context){
   
    if(!(status & ADC_STATUS_RESRDY)) return;
   
    if(isVAC){
        VAC = (float) ADC0_ConversionResultGet() * 375 / 65536;
        ADC0_ChannelSelect( ADC_POSINPUT_AIN10, ADC_NEGINPUT_GND); 
        isVAC= false;
        ADC0_ConversionStart();
      
    }else{
        IOUT = (float) ((((float) ADC0_ConversionResultGet() *4.95) / 65.535) - 2500)/100.0;
        IOUT = IOUT * 860/1200;
        if(IOUT<0) IOUT = 0;
        ADC0_ChannelSelect( ADC_POSINPUT_AIN5, ADC_NEGINPUT_GND); 
        isVAC= true;
        ADC0_ConversionStart();
        
    }
    ADC0Exec = true;
}

 
// Before to enter a running mode the following conditions shall be fullfilled
// - Precharge Activated
// - Power Contactor Activated
// - Min VAc max = 250V (180VAC) without Load

void InitializationLoop(void){
    
    uC_ENABLE_CONTACTOR_Set(); // Activates the Power Contactor
    mosfetActivation(false);
    alarm_overcurrent = false;
   
   
    uC_DISABLE_PRECHARGE_Set(); // Disable the precharge     
    ExecControl(true);
    TC0_TimerStart();
    return;
}

unsigned char comando = 0;
static volatile float value;
static bool RESET =true;

int main ( void )
{
    /* Initialize all modules */
    SYS_Initialize ( NULL );
    RESET =true;
    
    // LED initialization
    LED1_Clear();
    LED2_Clear();
    LED3_Clear();
    LED4_Clear();
    LED5_Clear();
    LED_FAULT_Clear();
    
    uC_DISABLE_PRECHARGE_Clear(); // Enable the precharge at the beginning
    
    WDT_Clear(); 
    
    // Registers the RTC interrupt routine to the RTC module
    RTC_Timer32CallbackRegister(rtcEventHandler, 0);
    RTC_Timer32Start(); // Start the RTC module
    
#ifdef CAN_BUS_ACTIVATION
    //Application Protocol initialization
    ApplicationProtocolInit();
#endif
    
    // INit the conversion of the AC input 
    ADC0_CallbackRegister( ADC0_Callback, 0 );
    ADC0_Enable();
    ADC0_ChannelSelect( ADC_POSINPUT_AIN5, ADC_NEGINPUT_GND); 
    ADC0_ConversionStart();
    isVAC= true;
    
    // INit the conversion of the Vout  
//    ADC1_CallbackRegister( ADC1_Callback, 0 );
    ADC1_Enable();
    ADC1_ConversionStart();
    
    // PRECHARGE INITIALIZATION 
    TC0_TimerCallbackRegister( TC0callback, 0 );
    
    // Disable Switching
    mosfetActivation(false);
    DAC_DataWrite(DAC_CHANNEL_0,0);
    
    main_fase = MAIN_FASE_INIT_LOOP;
   
   
    
    InitializationLoop();
    
    while( true )
    {
        /* Maintain state machines of all polled MPLAB Harmony modules. */
        SYS_Tasks ( );
               
        if(RESET){
            WDT_Clear(); 
            Iref = 0;
            if(trigger_time & _1024_ms_TriggerTime) RESET=false;
            else continue;
        }
        
        if(ADC0Exec)
        {
            ADC0ExecProcedure();
            ADC0Exec = false;
        }
        
        
        // Protocol management
        #ifdef CAN_BUS_ACTIVATION
            ApplicationProtocolLoop();
        #endif
        
        //
               
        if(trigger_time & _1024_ms_TriggerTime){
            trigger_time &=~ _1024_ms_TriggerTime;            
                        
            VITALITY_LED_Toggle();
            
            #ifdef CAN_BUS_ACTIVATION
                SystemACInputRegister.frequency = (unsigned char) inputFreq;
                value = maxVAC;
                SystemACInputRegister.max_ac_L = (unsigned char) ((unsigned short) value) ;
                SystemACInputRegister.max_ac_H = (unsigned char) ((unsigned short) value >> 8) ;
                encodeStatusRegister(&SystemACInputRegister);

                value = (unsigned short) (VOUT);
                SystemDCOutRegister.vout_L = (unsigned char) ((unsigned short) value) ;
                SystemDCOutRegister.vout_H = (unsigned char) ((unsigned short) value >> 8) ;
                value = IOUT*1000;
                SystemDCOutRegister.iout_L = (unsigned char) ((unsigned short) value) ;
                SystemDCOutRegister.iout_H = (unsigned char) ((unsigned short) value >> 8) ;
                encodeStatusRegister(&SystemDCOutRegister);
            #endif
            
            /*
             // Legge temperatura da I2 bus            
            SERCOM4_I2C_WriteRead(0x48, &comando, 1, &temperature, 1);
            SystemStatusRegister.temperature = temperature;
            encodeStatusRegister(&SystemStatusRegister);
            */
            
            
        }     
        
        if(trigger_time & _512_ms_TriggerTime){
            trigger_time &=~ _512_ms_TriggerTime;            
            
          
            
        }     
 
        // Timer events activated into the RTC interrupt
        if(trigger_time & _7820_us_TriggerTime){
            trigger_time &=~ _7820_us_TriggerTime;
            
            
        }

        if(trigger_time & _15_64_ms_TriggerTime){
            trigger_time &=~ _15_64_ms_TriggerTime;      
            
            if(alarm_vac_count){
                alarm_vac_count--;
                if(!alarm_vac_count) alarm_VAC = false;
            }
            
            if(alarm_VAC){
                LED_FAULT_Set();             
            }else LED_FAULT_Clear();
        }
        
       
       
    }

    /* Execution should not come here during normal operation */

    return ( EXIT_FAILURE );
}

/** @}*/
/*******************************************************************************
 End of File
*/

